export const testschuleName: string = 'Testschule Schulportal';
export const testschuleDstNr: string = '1111111';
export const testschule665Name: string = "Testschule-PW665";
export const testschule665DstNr: string = '1111165';
export const ersatzTestschuleName: string = 'Duborg-Skolen';
export const ersatzTestschuleDstNr: string = '0799801';
export const landSH: string = 'Land Schleswig-Holstein';
export const ersatzLandSH: string = 'Ersatzschulen Land Schleswig-Holstein';
export const oeffentlichLandSH:string = 'Öffentliche Schulen Land Schleswig-Holstein';
