export const schuelerRolle = 'itslearning-Schüler';
export const landesadminRolle = 'Landesadministrator';
export const schuladminOeffentlichRolle = 'Schuladministrator öffentlich';
export const lehrkraftOeffentlichRolle = 'Lehrkraft';
export const lehrkraftInVertretungRolle = 'LiV';
export const religionslehrkraftRolle = 'Ev./Kat. Religionslehrkraft';
export const itslearningLehrkraftRolle = 'itslearning-Lehrkraft';
export const pilotProjektSchulverwaltungskraftRolle = 'Pilotprojekt-Schulverwaltungskraft';
export const iQshMitarbeiterRolle = 'IQSH Mitarbeiter';
