name: Update Semver Tags

on:
  push:
    tags:
      - '*.*.*'
      
permissions:
  contents: write

jobs:
  update-semver-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  #v6.0.3
      
      - name: Update Semver
        uses: rickstaa/action-update-semver@77e8cb0f3cd805b38ffe25c07236336e05dcb4da #v1.1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          major_version_tag_only: false