name: "Check with Sonarcloud"

on:
  push:
    branches-ignore:
      - 'main'

concurrency:
  group: schulportal-testautomatisierung-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  sonarcloud:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-nest-test-sonarcloud.yaml@DBP-332-sonarcloud
    with:
      node_version: '18'
      deploy_stage: 'dev'
      skip_tests: true
    permissions:
      contents: read
    secrets: inherit