name: Playwright Tests
on:
  workflow_call:
    inputs:
      frontendHostname:
        type: string
        description: 'Hostname of the frontend server (optional)'
        required: false
  workflow_dispatch:
    inputs:
      frontendHostname:
        type: string
        description: 'Hostname of the frontend server (optional)'
        required: false
  push:
    branches: [ main ]

jobs: 
  run_playwright_end2end_tests:
    continue-on-error: true
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
     
    - name: If input frontendHostname is given, set env variable
      if: ${{ github.event.inputs.frontendHostname }}
      run: echo "FRONTEND_URL=https://${frontendHostname}/" >> $GITHUB_ENV
      
    - uses: actions/checkout@v3
      with:
        repository: 'dBildungsplattform/schulportal-testautomatisierung'
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
      env:
        USER: '${{ secrets.USER }}'
        PW: '${{ secrets.PW }}'
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30npm login
    
