# If you merge changes to this file, you will become the actor for the scheduled runs.
# Execution can only happen while the account of the actor is active.
name: Stage Smoke Test

on:
  schedule:
    - cron: '45 6 * * *'
      timezone: 'Europe/Berlin'

jobs:
  stage_smoke_test:
    uses: ./.github/workflows/run-playwright.yml
    with:
      frontendHostname: spsh.staging.spsh.dbildungsplattform.de
      tag: smoke
      browser: chromium
      playwright_branch: main
      send_notifications: true
    secrets:
      USER: ${{ secrets.USER }}
      PW: ${{ secrets.PW }}
      OTP_SEED_B32: ${{ secrets.OTP_SEED_B32 }}
      RC_WEBHOOK: ${{ secrets.RC_WEBHOOK }}
