# If you merge changes to this file, you will become the actor for the scheduled runs.
# Execution can only happen while the account of the actor is active.
name: Scheduled runs
run-name: "${{ github.event_name == 'workflow_dispatch' && format('Browser Test - {0}', github.event.inputs.browser) || 'Dispatch' }}"

on:
  schedule:
    - cron: '0 3 * * 1-5'
      timezone: 'Europe/Berlin'

  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: 'Browser to test'
        # required: true
        options:
          - chrome
          - firefox
          - webkit
          - msedge

jobs:
  dispatch_browser_tests:
    if: github.event.schedule == '0 3 * * 1-5' || (github.event_name == 'workflow_dispatch' && github.event.inputs.browser == '')
    runs-on: ubuntu-latest
    permissions:
      actions: write
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, webkit, msedge]
    steps:
      - run: gh workflow run run-playwright-scheduled.yml --repo "${{ github.repository }}" --ref "${{ github.ref }}" -f browser="${{ matrix.browser }}"
        env:
          GH_TOKEN: ${{ github.token }}

  browser_test:
    # if: github.event_name == 'workflow_dispatch'
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.browser != ''
    uses: ./.github/workflows/run-playwright.yml
    with:
      frontendHostname: main.dev.spsh.dbildungsplattform.de
      tag: dev
      browser: ${{ inputs.browser }}
      playwright_branch: main
      send_notifications: true
    secrets:
      SPSH_DEV_USER_SSHKEY: ${{ secrets.SPSH_DEV_USER_SSHKEY }}
      SPSH_DEV_KUBECONFIG: ${{ secrets.SPSH_DEV_KUBECONFIG }}
      SPSH_DEV_TUNNEL_USERNAME: ${{ secrets.SPSH_DEV_TUNNEL_USERNAME }}
      SPSH_DEV_TUNNEL_HOST: ${{ secrets.SPSH_DEV_TUNNEL_HOST }}
      SPSH_DEV_TUNNEL_PORT: ${{ secrets.SPSH_DEV_TUNNEL_PORT }}
      USER: ${{ secrets.USER }}
      PW: ${{ secrets.PW }}
      OTP_SEED_B32: ${{ secrets.OTP_SEED_B32 }}
      RC_WEBHOOK: ${{ secrets.RC_WEBHOOK }}
