name: After Push to base

on:
  push:
    branches:
      - main

jobs:
  run_playwright_tests:
      uses: ./.github/workflows/run-playwright.yml
      with:
        frontendHostname: main.dev.spsh.dbildungsplattform.de
        tag: dev
        browser: chromium
        playwright_branch: main
      secrets:
        USER: ${{ secrets.USER }}
        PW: ${{ secrets.PW }}
        OTP_SEED_B32: ${{ secrets.OTP_SEED_B32 }}
        RC_WEBHOOK: ${{ secrets.RC_WEBHOOK }}
